import { stringArg } from '../arguments.js';
import type { McpToolRegistry } from '../tool-registry.js';
import { objectSchema, projectIdSchema, stringSchema } from './schema-helpers.js';
import type { ProjectFileService } from '../../files/file-service.js';

const sha256Schema = { type: 'string', pattern: '^[A-Fa-f0-9]{64}$', minLength: 64, maxLength: 64 } as const;

export function registerFileTools(registry:McpToolRegistry,files:ProjectFileService):void{
  registry.register({definition:{name:'list_files',description:'List files inside one project sandbox.',inputSchema:objectSchema({project_id:projectIdSchema,path:stringSchema},['project_id'])},permission:'files:read',projectArgument:'project_id',handler:async(args,ctx)=>files.listFiles(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'path',{optional:true})??'.')});
  registry.register({definition:{name:'read_file',description:'Read one non-sensitive file inside a project sandbox and return its SHA-256 version.',inputSchema:objectSchema({project_id:projectIdSchema,path:stringSchema},['project_id','path'])},permission:'files:read',projectArgument:'project_id',handler:async(args,ctx)=>files.readFileSnapshot(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'path')??'')});
  registry.register({definition:{name:'search_files',description:'Search bounded project files for literal text.',inputSchema:objectSchema({project_id:projectIdSchema,query:stringSchema},['project_id','query'])},permission:'files:read',projectArgument:'project_id',handler:async(args,ctx)=>files.searchFiles(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'query',{max:4096})??'')});
  registry.register({definition:{name:'write_file',description:'Atomically write a bounded non-sensitive file inside a project sandbox.',inputSchema:objectSchema({project_id:projectIdSchema,path:stringSchema,content:stringSchema},['project_id','path','content'])},permission:'files:write',projectArgument:'project_id',handler:async(args,ctx)=>{await files.writeFile(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'path')??'',stringArg(args,'content')??'');return{ok:true};}});
  registry.register({definition:{name:'edit_file',description:'Atomically replace one unique text fragment only when the file SHA-256 still matches the prior read.',inputSchema:objectSchema({project_id:projectIdSchema,path:stringSchema,expected:stringSchema,replacement:stringSchema,expected_sha256:sha256Schema},['project_id','path','expected','replacement','expected_sha256'])},permission:'files:write',projectArgument:'project_id',handler:async(args,ctx)=>{await files.editFile(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'path')??'',stringArg(args,'expected')??'',stringArg(args,'replacement')??'',stringArg(args,'expected_sha256',{max:64})??'');return{ok:true};}});
  registry.register({definition:{name:'delete_file',description:'Delete one regular non-sensitive project file. Directories are not deleted.',inputSchema:objectSchema({project_id:projectIdSchema,path:stringSchema},['project_id','path'])},permission:'files:write',projectArgument:'project_id',handler:async(args,ctx)=>{await files.deleteFile(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'path')??'');return{ok:true};}});
}
