import { booleanArg, numberArg, stringArg, stringArrayArg } from '../arguments.js';
import type { McpToolRegistry } from '../tool-registry.js';
import { objectSchema, projectIdSchema, stringSchema } from './schema-helpers.js';
import type { GitService } from '../../git/git-service.js';
import type { JobManager } from '../../jobs/job-manager.js';
import type { LocalValidationPipeline } from '../../validation/local-ci.js';

export function registerGitCommandTools(registry:McpToolRegistry,git:GitService,jobs:JobManager,validation:LocalValidationPipeline):void{
  registry.register({definition:{name:'git_status',description:'Get bounded Git status for a project.',inputSchema:objectSchema({project_id:projectIdSchema},['project_id'])},permission:'git:read',projectArgument:'project_id',handler:async(args,ctx)=>git.status(stringArg(args,'project_id')??'',ctx.principal)});
  registry.register({definition:{name:'git_diff',description:'Get bounded Git diff for a project.',inputSchema:objectSchema({project_id:projectIdSchema,staged:{type:'boolean'}},['project_id'])},permission:'git:read',projectArgument:'project_id',handler:async(args,ctx)=>git.diff(stringArg(args,'project_id')??'',ctx.principal,booleanArg(args,'staged',true)??false)});
  registry.register({definition:{name:'git_log',description:'Get recent Git history.',inputSchema:objectSchema({project_id:projectIdSchema,limit:{type:'number',minimum:1,maximum:100}},['project_id'])},permission:'git:read',projectArgument:'project_id',handler:async(args,ctx)=>git.log(stringArg(args,'project_id')??'',ctx.principal,numberArg(args,'limit',{optional:true,min:1,max:100})??20)});
  registry.register({definition:{name:'git_branch',description:'Get the current Git branch.',inputSchema:objectSchema({project_id:projectIdSchema},['project_id'])},permission:'git:read',projectArgument:'project_id',handler:async(args,ctx)=>git.branch(stringArg(args,'project_id')??'',ctx.principal)});
  registry.register({definition:{name:'git_commit',description:'Create a Git commit containing only explicitly listed project paths. Existing unrelated staged changes are excluded.',inputSchema:objectSchema({project_id:projectIdSchema,message:stringSchema,paths:{type:'array',items:{type:'string'},minItems:1,maxItems:256}},['project_id','message','paths'])},permission:'git:write',projectArgument:'project_id',handler:async(args,ctx)=>git.commit(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'message',{max:200})??'',stringArrayArg(args,'paths')??[])});
  registry.register({definition:{name:'run_command',description:'Start one project-registered command as a persistent bounded job. Arbitrary argv and shell strings are not accepted.',inputSchema:objectSchema({project_id:projectIdSchema,command_id:stringSchema},['project_id','command_id'])},permission:'commands:run',projectArgument:'project_id',handler:async(args,ctx)=>jobs.start(stringArg(args,'project_id')??'',ctx.principal,stringArg(args,'command_id',{max:128})??'')});
  registry.register({definition:{name:'run_tests',description:'Start the project registered test command as a persistent bounded job.',inputSchema:objectSchema({project_id:projectIdSchema},['project_id'])},permission:'commands:run',projectArgument:'project_id',handler:async(args,ctx)=>jobs.start(stringArg(args,'project_id')??'',ctx.principal,'test')});
  registry.register({definition:{name:'run_validation',description:'Run the project Local CI pipeline for an existing task.',inputSchema:objectSchema({project_id:projectIdSchema,task_id:stringSchema},['project_id','task_id'])},permission:'commands:run',projectArgument:'project_id',handler:async(args,ctx)=>validation.run(stringArg(args,'task_id')??'',stringArg(args,'project_id')??'',ctx.principal)});
}
